# extends docker-compose.base.yml
version: "3.7"
services:
  php:
    build:
      dockerfile: './docker/prod/php-fpm/Dockerfile'
  apache:
    build:
      dockerfile: './docker/prod/apache/Dockerfile'
    logging:
      driver: none
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /tmp/doc/openapi.yaml
      PORT: 8080
      URLS: "[ { url: \"./openapi.yaml\", name: \"CashDesk API\" } ]"
    volumes:
      - ../doc:/tmp/doc
    networks:
      - backend
    logging:
      driver: none
  mongo:
    logging:
      driver: none
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: