# extends docker-compose.base.yml
version: "3.7"
services:
  php:
    build:
      dockerfile: './docker/prod/php-fpm/Dockerfile'
  apache:
    build:
      dockerfile: './docker/prod/apache/Dockerfile'
    logging:
      driver: none
  mongo:
    logging:
      driver: none
    volumes:
      - mongo-data:/data/db
  swagger:
    logging:
      driver: none
volumes:
  mongo-data: